CNST_DIRECTION_LEFT = -1
CNST_DIRECTION_RIGHT = 1
CNST_STATE_IDLE = 0
CNST_STATE_RUN = 1

CNST_DATA_KEY_IDLE = 'idle'
CNST_DATA_KEY_FACE = 'face'
CNST_DATA_KEY_DEFAULT = 'default'
CNST_DATA_KEY_DIALOG = 'dialog'
CNST_DATA_KEY_EFFECT = 'effect'
CNST_DATA_KEY_STATS = 'stats'


CNST_EMOTION_NORMAL = 'normal'
CNST_EMOTION_SUS = 'sus'

CNST_NPC_BUTTON_TYPE_NONE = 0
CNST_NPC_BUTTON_TYPE_TALK = 1
CNST_NPC_BUTTON_TYPE_ACTION = 2
CNST_NPC_BUTTON_TYPE_INSPECT = 3

CNST_GAME_TIME_MORNING = 0
CNST_GAME_TIME_NOON = 1
CNST_GAME_TIME_AFTERNOON = 2
CNST_GAME_TIME_EVENING = 3
CNST_GAME_TIME_NIGHT = 4


CNST_GAME_DAY_SUNDAY = 0
CNST_GAME_DAY_MONDAY = 1
CNST_GAME_DAY_TUESDAY = 2
CNST_GAME_DAY_WEDNESDAY = 3
CNST_GAME_DAY_THURSDAY = 4
CNST_GAME_DAY_FRIDAY = 5
CNST_GAME_DAY_SATURDAY = 6