CNST_DIRECTION_LEFT = -1
CNST_DIRECTION_RIGHT = 1
CNST_STATE_IDLE = 0
CNST_STATE_RUN = 1

CNST_DATA_KEY_IDLE = 'idle'
CNST_DATA_KEY_FACE = 'face'
CNST_DATA_KEY_DEFAULT = 'default'
CNST_DATA_KEY_DIALOG = 'dialog'
CNST_DATA_KEY_EFFECT = 'effect'
CNST_DATA_KEY_STATS = 'stats'


CNST_EMOTION_NORMAL = 'normal'
CNST_EMOTION_SUS = 'sus'

CNST_NPC_BUTTON_TYPE_NONE = 0
CNST_NPC_BUTTON_TYPE_TALK = 1
CNST_NPC_BUTTON_TYPE_ACTION = 2
CNST_NPC_BUTTON_TYPE_INSPECT = 3