CNST_DIRECTION_LEFT = -1
CNST_DIRECTION_RIGHT = 1
CNST_STATE_IDLE = 0
CNST_STATE_RUN = 1

CNST_DATA_KEY_IDLE = 'idle'
CNST_DATA_KEY_FACE = 'face'
CNST_DATA_KEY_DEFAULT = 'default'
CNST_DATA_KEY_CONDITION = 'condition'
CNST_DATA_KEY_POSITION = 'position'
CNST_DATA_KEY_DIALOG = 'dialog'
CNST_DATA_KEY_EFFECT = 'effect'
CNST_DATA_KEY_STATS = 'stats'
CNST_DATA_KEY_LOCATIONS = 'locations'


CNST_EMOTION_NORMAL = 'normal'
CNST_EMOTION_SUS = 'sus'

CNST_NPC_BUTTON_TYPE_NONE = 0
CNST_NPC_BUTTON_TYPE_TALK = 1
CNST_NPC_BUTTON_TYPE_ACTION = 2
CNST_NPC_BUTTON_TYPE_INSPECT = 3

CNST_GAME_TIME_MORNING = 0
CNST_GAME_TIME_NOON = 1
CNST_GAME_TIME_AFTERNOON = 2
CNST_GAME_TIME_EVENING = 3
CNST_GAME_TIME_NIGHT = 4


CNST_GAME_DAY_SUNDAY = 0
CNST_GAME_DAY_MONDAY = 1
CNST_GAME_DAY_TUESDAY = 2
CNST_GAME_DAY_WEDNESDAY = 3
CNST_GAME_DAY_THURSDAY = 4
CNST_GAME_DAY_FRIDAY = 5
CNST_GAME_DAY_SATURDAY = 6

#PLACES

CNST_GAME_LOCATION_TOWN_NAME = 'Ashport'
CNST_GAME_LOCATION_STREET_MAIN = 'Centra Avenue'
CNST_GAME_LOCATION_STREET_RICH = 'Sterling Lane'
CNST_GAME_LOCATION_STREET_GHETTO = 'Dockside Drive'

CNST_GAME_LOCATION_STREET_MAIN_BANK = 'Horizon Trust'
CNST_GAME_LOCATION_STREET_MAIN_BANK_HALL = 'Horizon Trust Hallway'
CNST_GAME_LOCATION_STREET_MAIN_BANK_BACK_OFFICE = 'Horizon Trust Office'
CNST_GAME_LOCATION_STREET_MAIN_BANK_SAFE = 'Horizon Trust Safe'
CNST_GAME_LOCATION_STREET_MAIN_STADIUM = 'Titan Field'
CNST_GAME_LOCATION_STREET_MAIN_STADIUM_FIELD = 'Titan Field Center field'
CNST_GAME_LOCATION_STREET_MAIN_STADIUM_ENTRANCE = 'Titan Field Entrance'
CNST_GAME_LOCATION_STREET_MAIN_STADIUM_STANDS = 'Titan Field Stands'
CNST_GAME_LOCATION_STREET_MAIN_STADIUM_VIP_LOUNGE = 'Titan Field VIP Lounge'
CNST_GAME_LOCATION_STREET_MAIN_SCHOOL = 'Ashport Central School'
CNST_GAME_LOCATION_STREET_MAIN_SCHOOL_HALLWAY_GROUND = 'School Ground Hallway'
CNST_GAME_LOCATION_STREET_MAIN_SCHOOL_HALLWAY_1ST_FLOOR = 'School 2nd floor Hallway'
CNST_GAME_LOCATION_STREET_MAIN_SCHOOL_HALLWAY_2ND_FLOOR = 'School 3rd floor Hallway'
CNST_GAME_LOCATION_STREET_MAIN_SCHOOL_SCIENCE_ROOM = 'School Science Room'
CNST_GAME_LOCATION_STREET_MAIN_SCHOOL_MATH_ROOM = 'School Math Room'
CNST_GAME_LOCATION_STREET_MAIN_SCHOOL_MUSIC_ROOM = 'School Music Room'
CNST_GAME_LOCATION_STREET_MAIN_SCHOOL_SPANISH_ROOM = 'School Spanish Room'
CNST_GAME_LOCATION_STREET_MAIN_SCHOOL_COMPUTER_ROOM = 'School Computer Room'
CNST_GAME_LOCATION_STREET_MAIN_SCHOOL_STAGE = 'School Stage'
CNST_GAME_LOCATION_STREET_MAIN_SCHOOL_OVAL = 'School Oval'
CNST_GAME_LOCATION_STREET_MAIN_SCHOOL_GIRLS_BATHROOM = 'School Girl\'s Bathroom'
CNST_GAME_LOCATION_STREET_MAIN_SCHOOL_BOYS_BATHROOM = 'BSchool oy\'s Bathroom'
CNST_GAME_LOCATION_STREET_MAIN_SCHOOL_STOCK_ROOM = 'School Stock Room'
CNST_GAME_LOCATION_STREET_MAIN_GYM = 'Gym'
CNST_GAME_LOCATION_STREET_MAIN_GYM_HALLWAY = 'Gym Hallway'
CNST_GAME_LOCATION_STREET_MAIN_GYM_RESTROOM = 'Gym Rest Room'
CNST_GAME_LOCATION_STREET_MAIN_HOSPITAL = 'Centra Hospital'
CNST_GAME_LOCATION_STREET_MAIN_HOSPITAL_GROUND_FLOOR = 'Hospital Ground Floor'
CNST_GAME_LOCATION_STREET_MAIN_HOSPITAL_EMERGENCY = 'Hospital Emergency Room'
CNST_GAME_LOCATION_STREET_MAIN_HOSPITAL_ROOM_1_1 = 'Hospital Room 11'
CNST_GAME_LOCATION_STREET_MAIN_HOSPITAL_ROOM_1_2 = 'Hospital Room 12'
CNST_GAME_LOCATION_STREET_MAIN_HOSPITAL_CUBICLE = 'Hospital Cubicle'
CNST_GAME_LOCATION_STREET_MAIN_HOSPITAL_2ND_FLOOR = 'Hospital 2nd Floor'
CNST_GAME_LOCATION_STREET_MAIN_HOSPITAL_ICU = 'Hospital ICU'
CNST_GAME_LOCATION_STREET_MAIN_HOSPITAL_ROOM_2_1 = 'Hospital Room 21'
CNST_GAME_LOCATION_STREET_MAIN_HOSPITAL_ROOM_2_2 = 'Hospital Room 22'
CNST_GAME_LOCATION_STREET_MAIN_HOSPITAL_OPERATION_ROOM = 'Hospital Operation Room'
CNST_GAME_LOCATION_STREET_MAIN_POLICE_STATION = 'Centra Police Station'
CNST_GAME_LOCATION_STREET_MAIN_POLICE_STATION_HALLWAY = 'Centra Police Station Hallway'
CNST_GAME_LOCATION_STREET_MAIN_POLICE_STATION_JAIL = 'Centra Police Station Jail'
CNST_GAME_LOCATION_STREET_MAIN_POLICE_STATION_CUBICLE = 'Centra Police Station Cubicle'
CNST_GAME_LOCATION_STREET_MAIN_PARK = 'Centra Park'
CNST_GAME_LOCATION_STREET_MAIN_PARK_SECRET_PLACE = 'Centra Park Secret Place'
CNST_GAME_LOCATION_STREET_MAIN_MALL = 'Centra Mall'
CNST_GAME_LOCATION_STREET_MAIN_MALL_GROCERY = 'Centra Mall Grocery'
CNST_GAME_LOCATION_STREET_MAIN_MALL_CLOTHING = 'Centra Mall Clothing'
CNST_GAME_LOCATION_STREET_MAIN_MALL_JEWELRY = 'Centra Mall Jewelry'
CNST_GAME_LOCATION_STREET_MAIN_MALL_GAMING = 'Centra Mall Gaming'
CNST_GAME_LOCATION_STREET_MAIN_MALL_FLOWER = 'Centra Mall Flower'
CNST_GAME_LOCATION_STREET_MAIN_MALL_THEATER = 'Centra Mall Theater'
CNST_GAME_LOCATION_STREET_MAIN_MALL_HARDWARE = 'Centra Mall Hardware'


CNST_GAME_LOCATION_STREET_RICH_POLICE_STATION = 'Sterling Police Station'
CNST_GAME_LOCATION_STREET_RICH_POLICE_STATION_HALLWAY = 'Sterling Police Station Hallway'
CNST_GAME_LOCATION_STREET_RICH_POLICE_STATION_JAIL = 'Sterling Police Station Jail'
CNST_GAME_LOCATION_STREET_RICH_POLICE_STATION_CUBICLE = 'Sterling Police Station Cubicle'
CNST_GAME_LOCATION_STREET_RICH_DONUT_SHOP = 'Hole-in-One Bakery'
CNST_GAME_LOCATION_STREET_RICH_DONUT_SHOP_HALLWAY = 'Hole-in-One Bakery Hallway'
CNST_GAME_LOCATION_STREET_RICH_DONUT_SHOP_KITCHEN = 'Hole-in-One Bakery Kitchen'
CNST_GAME_LOCATION_STREET_RICH_CLUB = 'Luxe Noir'
CNST_GAME_LOCATION_STREET_RICH_CLUB_HALLWAY = 'Luxe Noir Hallway'
CNST_GAME_LOCATION_STREET_RICH_CLUB_BACKYARD = 'Luxe Noir Backyard'
CNST_GAME_LOCATION_STREET_RICH_CLUB_CUBICLE_1 = 'Luxe Noir Cubicle 1'
CNST_GAME_LOCATION_STREET_RICH_CLUB_CUBICLE_2 = 'Luxe Noir Cubicle 2'
CNST_GAME_LOCATION_STREET_RICH_CLUB_BOOTH = 'Luxe Noir Booth'
CNST_GAME_LOCATION_STREET_RICH_CLUB_REST_ROOM = 'Luxe Noir Rest Room'

CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_1 = 'Hollow Flats'
CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_1_GROUND_FLOOR_HALLWAY = 'Hollow Flats Hallway'
CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_1_ROOM_1_1 = 'Hollow Flats Room 11'
CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_1_ROOM_1_2 = 'Hollow Flats Room 12'
CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_1_ROOM_1_3 = 'Hollow Flats Room 13'
CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_1_2ND_FLOOR_HALLWAY = 'Hollow Flats 2nd Floor Hallway'
CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_1_ROOM_2_1 = 'Hollow Flats Room 21'
CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_1_ROOM_2_2 = 'Hollow Flats Room 22'
CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_1_ROOM_2_3 = 'Hollow Flats Room 23'
CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_2 = 'Ironclad Flats'
CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_2_GROUND_FLOOR_HALLWAY = 'Ironclad Flats Hallway'
CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_2_ROOM_1_1 = 'Ironclad Flats Room 11'
CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_2_ROOM_1_2 = 'Ironclad Flats Room 12'
CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_2_ROOM_1_3 = 'Ironclad Flats Room 13'
CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_2_2ND_FLOOR_HALLWAY = 'Ironclad Flats 2nd Floor Hallway'
CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_2_ROOM_2_1 = 'Ironclad Flats Room 21'
CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_2_ROOM_2_2 = 'Ironclad Flats Room 22'
CNST_GAME_LOCATION_STREET_GHETTO_APARTMENT_2_ROOM_2_3 = 'Ironclad Flats Room 23'
CNST_GAME_LOCATION_STREET_GHETTO_ALLEYWAY_1 = 'Dockside Alleyway'
CNST_GAME_LOCATION_STREET_GHETTO_ALLEYWAY_2 = 'Pier Alleyway'
CNST_GAME_LOCATION_STREET_GHETTO_STRIP_CLUB = 'Neon Lust'
CNST_GAME_LOCATION_STREET_GHETTO_STRIP_CLUB_HALLWAY = 'Neon Lust Hallway'
CNST_GAME_LOCATION_STREET_GHETTO_STRIP_CLUB_BOOTH = 'Neon Lust Booth'
CNST_GAME_LOCATION_STREET_GHETTO_STRIP_CLUB_BACK_DOOR = 'Neon Lust Back Door'
CNST_GAME_LOCATION_STREET_GHETTO_STRIP_CLUB_REST_ROOM = 'Neon Lust Rest Room'
CNST_GAME_LOCATION_STREET_GHETTO_STRIP_CLUB_PRIVATE_ROOM = 'Neon Lust Private Room'
CNST_GAME_LOCATION_STREET_GHETTO_7_11 = '7/11'
CNST_GAME_LOCATION_STREET_GHETTO_ADULT_SHOP = 'Naughty Niche'
CNST_GAME_LOCATION_STREET_GHETTO_DRUG_DEN = 'Drug Den'
CNST_GAME_LOCATION_STREET_GHETTO_POLICE_STATION = 'Dockside Police Station'
CNST_GAME_LOCATION_STREET_GHETTO_PIER = 'Pier'

# BUFF

CNST_BUFF_MARY_01 =  'buff_mary_01'
CNST_BUFF_MARY_02 =  'buff_mary_02'
CNST_BUFF_MARY_03 =  'buff_mary_03'
CNST_BUFF_MARY_04 =  'buff_mary_04'
CNST_BUFF_MARY_05 =  'buff_mary_05'
CNST_BUFF_MARY_06 =  'buff_mary_06'